version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: airphm_sql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=airphm
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./Docker/init_db.sh:/docker-entrypoint-initdb.d/01_init_db.sh

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_airphm
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@phm.edu.ar
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  neo4j:
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/airphm/conf:/var/lib/neo4j/conf
      - ./data/airphm/data:/var/lib/neo4j/data
      - ./data/airphm/import:/var/lib/neo4j/import
      - ./data/airphm/logs:/var/lib/neo4j/logs
      - ./data/airphm/plugins:/var/lib/neo4j/plugins
    environment:
      server.memory.pagecache.size: 1G
      server.memory.heap.max_size: 1G# auth
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: neo4j/passw0rd

  redis:
    container_name: redis-airphm
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander-airphm
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  app:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: redis-node-airphm
    ports:
      - 4026:8080
    command: node RedisInit/cargaDatosInicial.js

volumes:
  db:
  pgadmin-data: