spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      #            use-new-id-generator-mappings: false
      format_sql: true
      ddl-auto: create-drop
      pool_size: 50
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27117,127.0.0.1:27118/lodgings?authSource=admin
      database: lodgings_test

logging:
  level:
    org.springframework.data: DEBUG
    org.mongodb.driver.protocol.command: DEBUG